name: Accessibility & Performance

on:
  push:
    branches: [main]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false 
          load: true
          tags: idilsaglam/mtssf:latest 
      - name: Run docker container 
        run: docker run -d --name idil-saglam-mtssf -P idilsaglam/mtssf:latest
      - name: Get port number
        run: |
          PORT=$(docker port idil-saglam-mtssf 8080/tcp | head -n1 | sed -E 's/.*:([0-9]+)$/\1/')
          echo "PORT=$PORT" >> "$GITHUB_ENV"
          echo "URL=http://localhost:${PORT}" >> "$GITHUB_ENV"
      - name: Show URL 
        uses: Makepad-fr/pa11y-action@v1.0.0
        with:
          url: $URL